import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Providers} from './providers'
import Link from 'next/link'
import NavbarNUI from '../components/navbars/NavbarNUI'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html  lang='en'>
      <body className={inter.className}>
        <Providers>
          <header className='py-6'>
            <NavbarNUI></NavbarNUI>

          </header>
          <main>{children}</main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  )
}
